### ISSUE TITLE
AAS JSON Deserialization error

### ISSUE THREAD

**Issue by akshaysharmank** [FraunhoferIOSB/FAAAST-Service#136]
**Describe the bug**
Not able to deserialize the AAS JSON file created with AASX Package Explorer.

![Deserialization error](https://user-images.githubusercontent.com/67057013/174014203-8d39b3a4-bd7f-4f54-b40a-2f950f7cd036.JPG)

**Output**
**io.adminshell.aas.v3.dataformat.DeserializationException:error reading AAS file - could be not parsed using any of the potential data formats identified by file extension (potential data formats: JSON)**

**Comment by JensMueller2709** [comment]
Hi,
thanks for using the FA³ST Service and creating the first bug issue! 

**To your problem:**
Unfortunately interoperability across different AAS tools is currently still an issue as different tools implement different versions of the specification and/or do not comply 100% with it.  This is also the case for AASX Package Explorer and FA³ST Service. 

**Our solution**
However, we have developed a [FA³ST Package Explorer Converter](https://github.com/FraunhoferIOSB/FAAAST-Package-Explorer-Converter) that allows to convert JSON files exported with the AASX Package Explorer to be used with FA³ST Service. 
Please be aware that this tool is considered **experimental** and may crash or fail to convert certain files. If you encounter anything like that, feel free to send us the file causing problems to clarify the problem (email at faaast@iosb.fraunhofer.de) or update the converter tool.

Is this answer helpful for you?
If you have any other questions, do not hesitate to create other issues or comment to this issue. 

Since this is not a bug in the FA³ST Service I change the label of this issue.

Best,
Jens

**Comment by akshaysharmank** [comment]
Thank you so much for the response! **FA³ST Package Explorer Converter** works fine for my aas json model!

Regards,
Akshaya
