### ISSUE TITLE
Some AAS Environment File Fails to Load

### ISSUE THREAD

**Issue by mehtanin** [FraunhoferIOSB/FAAAST-Service#195]
**Describe the bug**
Some aas environment files throw an exception while running the FAAAST service.

**To Reproduce**
1.  Go to the directory of the 'starter-0.2.0-SNAPSHOT.jar'
2.  Run in the command line 'java -jar starter-0.2.0-SNAPSHOT.jar --no-modelValidation -m 17_ABB.aasx'
3.  See the error

**Expected behavior**
FA³ST Service successfully started 
HTTP endpoint available on port **** 

**Output**
[ERROR] Error loading model file (de.fraunhofer.iosb.ilt.faaast.service.starter.App)
io.adminshell.aas.v3.dataformat.DeserializationException: error reading AAS file - could be not parsed using any of the potential data formats identified by file extension (potential data formats: AASX)
![image](https://user-images.githubusercontent.com/17111915/187432307-b5f5981f-a0e8-44cf-a60b-e0b105d57334.png)

**Attached is the Compressed Input AASX File**
17_ABB.aasx
[17_ABB.zip](https://github.com/FraunhoferIOSB/FAAAST-Service/files/9452635/17_ABB.zip)

**Comment by JensMueller2709** [comment]
Thank you very much for your report.

**To your problem:**
This is a known issue when loading aas models created with the AASX Package Converter within FA³ST Service. Unfortunately interoperability across different AAS tools is currently still an issue as different tools implement different versions of the specification and/or do not comply 100% with it. This is also the case for AASX Package Explorer and FA³ST Service.

**Our solution**
However, we have developed a [FA³ST Package Explorer Converter](https://github.com/FraunhoferIOSB/FAAAST-Package-Explorer-Converter) that allows to convert JSON files exported with the AASX Package Explorer to be used with FA³ST Service. 
Following steps converts the given incompatible aas model to a compatible version:

1. Save the given .aasx model file as .json using the AASX Package Explorer
2. Download the latest .jar from the FA³ST Package Explorer Converter which you can find [here](https://search.maven.org/remote_content?g=de.fraunhofer.iosb.ilt.faaast&a=package-explorer-converter&v=LATEST)
3. Convert the aas modell. Run    
`java -jar .\package-explorer-converter-0.2.0.jar -i 17_ABB.json -o 17_Converted_ABB.json`
4. Start the FA³ST Service   
`java -jar .\starter-0.3.0-SNAPSHOT.jar --endpoint=http  --no-modelValidation -m 17_Converted_ABB.json`

**Current Limitations**
The current version of the FA³ST Service cannot handle additional files which are included in .aasx files. However, this feature will be implemented in the next release of the FA³ST Service.

If you have any other questions, do not hesitate to create other issues or comment to this issue.

Since this is not a bug in the FA³ST Service I change the label of this issue.
