### ISSUE TITLE
OpenAPI Spec not on SwaggerHub

### ISSUE THREAD

**Issue by AjdinovicSamed** [FraunhoferIOSB/FAAAST-Service#513]
**Describe the bug**
I can't find the referenced specifications on swagger hub.

**To Reproduce**
You link to [V1.0RC01](https://app.swaggerhub.com/apis/Plattform_i40/Entire-Interface-Collection/V1.0RC01) in the docu but implement V1.0RC02 according to the readme.

**Comment by mjacoby** [comment]
The readme and documentation are indeed inconsistent with regard to the implemented version of the HTTP API. 

However, the issue is a bit more complex. The AAS specification part 2 v1.0RC01 seems to be no longer available online. the corresponding Swagger document can still be found online at https://app.swaggerhub.com/apis/Plattform_i40/Entire-Interface-Collection/V1.0RC01. After a deeper analysis, it seems that the Swagger documentation is not 100% compliant with the specification v1.0RC01 and actually closer to v1.0RC02.
There is also a swagger document labeled v1.0RC02 which seems to be in-line with the AAS specification part 2 v1.0RC02 available online at https://app.swaggerhub.com/apis/Plattform_i40/Entire-API-Collection/V1.0RC02.

After carefully comparing both Swagger documents, it seems that they are almost identically. The main differences are that v1.0RC02...

- defines two additional operations for handling File and Blob elements, namely GET and PUT `/submodel/submodel-elements/{idShortPath}/attachment`
- provides more details about expected return codes
- removed the `/registry` path prefix for operatiosn related to registry interfaces
- added explicit information that UTF-8 encoding should be used

As a consequence, I updated the readme and documentation to only refer to the v1.0RC02 specification as well as Swagger document.
Please be aware that FA³ST Service does not implement 100% of the API, e.g. it still does not support hosting files referenced by submodel elements of type `File` and therefore also does not support the above mentioned API calls for reading/writing these values.
