### ISSUE TITLE
Empty outputArguments v1.0

### ISSUE THREAD

**Issue by wssmd** [FraunhoferIOSB/FAAAST-Service#740]
**Describe the bug**
Executing an operation returns an empty list of outputArguments

**To Reproduce**
1. start a Service
2. invoke an operation that should return an output
3. These are my AAS-definition and Configuration (PS: FileStorage is not being read from config.json and must be added to the ServiceConfig object)
[aas.json](https://github.com/FraunhoferIOSB/FAAAST-Service/files/14824475/aas.json)
[config.json](https://github.com/FraunhoferIOSB/FAAAST-Service/files/14837079/config.json)

and this is the payload of the operation:
`{   
    "inoutputArguments": [],
    "inputArguments": [
        {
            "value": {
                "modelType": "Property",
                "valueType": "xs:integer",
                "idShort": "input1",
                "value": "3"
            }
        },
        {
            "value": {
                "modelType": "Property",
                "valueType": "xs:integer",
                "idShort": "input2",
                "value": "2"
            }
        }
    ],
    "clientTimeoutDuration": "PT1M"
}`

**Expected behavior**
`{
    "messages": [],
    "executionState": "Completed",
    "success": true,
    "outputArguments": [
      {
            "value": {
                "modelType": "Property",
                "valueType": "xs:integer",
                "idShort": "sum",
                "value": "5"
            }
        }
    ],
    "inoutputArguments": []
}`

**Output**
`{
    "messages": [],
    "executionState": "Completed",
    "success": true,
    "outputArguments": [],
    "inoutputArguments": []
}`

**Comment by mjacoby** [comment]
I was able to reproduce the problem and it seems to be caused by a combination of issues such as

- the AAS model is not valid (as it is using `inputVariable` instead of `inputVariables`) but is still loaded without any feedback to the user
- output says "Model successfully validated" although model validation is currently very limited (as the AAS4J library FA³ST Service is using did not yet update the model validation logic to v3.0 and therefore is currently not available)
- there is a bug with using `inoutputParameters` (which your model is using although your expected response contains only `outputArguments`

As a quick fix, you can change your model file like this [aas-fixed.json](https://github.com/FraunhoferIOSB/FAAAST-Service/files/14848415/aas-fixed.json).

The changes I made are renaming input-/output-/inoutputVariable to input-/output-/inoutputVariable**s** (with additional s at the end) and moving the expected result property `sum` from inoutputVariables to outputVariables. 
Using this updated model it did work for me. Please let me know if this is not working for you.

We will also work on addressing the above mentioned issues in the near future.

**Comment by wssmd** [comment]
The updated model solves the problem. Thank you.
Just a reminder that FileStorage is not read from the configuration file and must be manually added to the ServiceConfig object.

**Comment by mjacoby** [comment]
Thank you for the feedback. I also figured out the cause of your problem with with filestorage and the reason is that there are some errors in the documentation which caused your configuration to be incorrect.

The correct filestorage part of your config should look like this
```JSON
"fileStorage": {
  "@class": "de.fraunhofer.iosb.ilt.faaast.service.filestorage.memory.FileStorageInMemory"
}
```

I also fixed the documentation accordingly.
